services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: 'infragame'
    ports:
      - 3306:3306
    hostname: mysql

  server:
    build: ./server
    container_name: express
    ports:
      - 5000:5000
    volumes:
      - ./server:/app/server
    command: npm run start

  client:
    build: .
    container_name: react
    ports:
      - 3000:3000
    links:
      - server
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run start -openssl-legacy-provider
