version: '3.3'
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '9908'
      MYSQL_DATABASE: 'infragame_dev'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - 3306:3306
    hostname: mysql

  server:
    build: ./middleware-develop
    container_name: express
    depends_on:
      - "db"
    links:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./middleware-develop:/home/node/app/
    command: npm run start
  client:
    build: ./Interface-develop/
    container_name: react
    ports:
      - 3000:3000
    links:
      - server
    volumes:
      - ./Interface-develop/src:/app/src
      - ./Interface-develop/public:/app/public